// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbkRYgIZeHTul5vRKPWSdOXDweyPnTj8s',
    appId: '1:372136938768:web:e6711ba804b56b68572995',
    messagingSenderId: '372136938768',
    projectId: 'codiaadv-826b2',
    authDomain: 'codiaadv-826b2.firebaseapp.com',
    storageBucket: 'codiaadv-826b2.firebasestorage.app',
    measurementId: 'G-P6W97DH1DP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3wCdPQqfaP11ax34vyzusEQTItVK_HCU',
    appId: '1:372136938768:android:0102547219be2e20572995',
    messagingSenderId: '372136938768',
    projectId: 'codiaadv-826b2',
    storageBucket: 'codiaadv-826b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcqx9yVbVmUJkdSHlVxAMhNdFIjtVn0hQ',
    appId: '1:372136938768:ios:d2356ea053d6154b572995',
    messagingSenderId: '372136938768',
    projectId: 'codiaadv-826b2',
    storageBucket: 'codiaadv-826b2.firebasestorage.app',
    iosBundleId: 'com.example.codiaAdv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbkRYgIZeHTul5vRKPWSdOXDweyPnTj8s',
    appId: '1:372136938768:web:101aba26a0399a09572995',
    messagingSenderId: '372136938768',
    projectId: 'codiaadv-826b2',
    authDomain: 'codiaadv-826b2.firebaseapp.com',
    storageBucket: 'codiaadv-826b2.firebasestorage.app',
    measurementId: 'G-9NNX79Q5YT',
  );
}
